version: 0.0
os: linux
files:
  - source: /
    destination: /var/flaskapp/flask

hooks:
  ApplicationStart:
    - location: common_utilities/shell_scripts/after_deploy_supervisor_restart.sh
      timeout: 500
      runas: root