image: python:3.7.3

pipelines:
  branches:
    master:
    - step:
        name: Build for Master branch
        caches:
          - pip
        script:
          - apt-get update
          - python3 -m pip install --upgrade --force pip
          - pip3 install -r requirements.txt
          - apt-get install -y zip
          - zip -r mainserver-backend.zip .
        artifacts:
          - mainserver-backend.zip
    - step:
        name: Uploading Master branch to S3
        caches:
          - pip
        script:
          - pipe: atlassian/aws-code-deploy:0.5.3
            variables:
              COMMAND: 'upload'
              S3_BUCKET: $S3_BUCKET
              VERSION_LABEL: 'my-app-1.0.0'
              ZIP_FILE: 'mainserver-backend.zip'
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              APPLICATION_NAME: 'AWSCodeDeployApplication'
              AWS_SECRET_ACCESS_KEY: $AWS_ACCESS_SECRET_KEY_ID
    - step:
        name: Deploying Master branch on Main Server
        deployment: Production
        caches:
          - pip
        script:
          - pipe: atlassian/aws-code-deploy:0.5.3
            variables:
              WAIT: 'true'
              COMMAND: 'deploy'
              S3_BUCKET: $S3_BUCKET
              VERSION_LABEL: 'my-app-1.0.0'
              FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              DEPLOYMENT_GROUP: 'MainServer-Backend'
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              IGNORE_APPLICATION_STOP_FAILURES: 'true'
              APPLICATION_NAME: 'AWSCodeDeployApplication'
              AWS_SECRET_ACCESS_KEY: $AWS_ACCESS_SECRET_KEY_ID
