image: python:3.7.3

pipelines:
  branches:
    test_server:
    - step:
        name: Build
        caches:
          - pip
        script:
          - apt-get update
          - python3 -m pip install --upgrade --force pip
          - pip3 install -r requirements.txt
          - apt-get install -y zip
          - zip -r backend-test-server.zip .
        artifacts:
          - backend-test-server.zip
    - step:
        name: Uploading to S3
        caches:
          - pip
        script:
          - pipe: atlassian/aws-code-deploy:0.5.3
            variables:
              COMMAND: 'upload'
              VERSION_LABEL: 'my-app-1.0.0'
              AWS_DEFAULT_REGION: 'us-west-1'
              ZIP_FILE: 'backend-test-server.zip'
              S3_BUCKET: 'sample-codebucket-guide'
              APPLICATION_NAME: 'BackendCodeDeploy'
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_ACCESS_SECRET_KEY_ID
    - step:
        name: Deploying on Test Server
        deployment: Production
        caches:
          - pip
        script:
          - pipe: atlassian/aws-code-deploy:0.5.3
            variables:
              WAIT: 'true'
              COMMAND: 'deploy'
              VERSION_LABEL: 'my-app-1.0.0'
              AWS_DEFAULT_REGION: 'us-west-1'
              DEPLOYMENT_GROUP: 'Test-Branch'
              FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
              S3_BUCKET: 'sample-codebucket-guide'
              APPLICATION_NAME: 'BackendCodeDeploy'
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              IGNORE_APPLICATION_STOP_FAILURES: 'true'
              AWS_SECRET_ACCESS_KEY: $AWS_ACCESS_SECRET_KEY_ID